spring:
  cloud:
    stream:
      bindings:
        input:
          destination: batch.updates
          group: stock

management:
  endpoints:
    web:
      exposure:
        include: health, info
